/**
 * General info: https://www.medicalnewstoday.com/articles/266765
 *
 * Nutrition Facts: https://fdc.nal.usda.gov/api-guide.html#bkmk-1
 *
 * https://www.gatsbyjs.org/docs/programmatically-create-pages-from-data/
 */

exports.sourceNodes = ({ actions, createNodeId, createContentDigest }) => {
  const vegetables = [
    {
      name: 'Asparagus',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [5, 6],
      location: 'New York',
      generalInfo:
        'Eat it raw or cooked, and in dishes such as soups, stews, salads, or on its own.',
      nutritionInfo:
        'The nutrients in asparagus can support heart and bone health, while the folate and iron that it contains may be especially beneficial during pregnancy.',
    },
    {
      name: 'Beans, String',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [7, 8, 9, 10],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Beans, Shell',
      type: 'VEGETABLE',
      storageMonths: [1, 2, 3, 4, 5, 6, 7],
      freshMonths: [9, 10, 11, 12],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Beets',
      type: 'VEGETABLE',
      storageMonths: [1, 2, 12],
      freshMonths: [6, 7, 8, 9, 10, 11],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Beet Greens',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [5, 6, 7, 8, 9],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Broccoli',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [6, 7, 8, 9, 10, 11],
      location: 'New York',
      generalInfo:
        'Broccoli has a reputation as a superfood. It is low in calories but contains a wealth of nutrients and antioxidants that support many aspects of human health.',
    },
    {
      name: 'Brussels Sprouts',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [9, 10, 11],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Cabbage',
      type: 'VEGETABLE',
      storageMonths: [1, 2, 3, 12],
      freshMonths: [5, 6, 7, 8, 9, 10, 11],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Carrots',
      type: 'VEGETABLE',
      storageMonths: [1, 2, 3, 12],
      freshMonths: [6, 7, 8, 9, 10, 11],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Cauliflower',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [8, 9, 10, 11],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Celery',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [8, 9, 10],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Collard Greens',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [7, 8, 9, 10, 11, 12],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Corn',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [7, 8, 9, 10],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Cucumbers',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [7, 8, 9],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Eggplant',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [8, 9, 10],
      location: 'New York',
      generalInfo: '',
    },
    // {
    //     name: 'Fennel',
    //     type: 'VEGETABLE',
    //     storageMonths: [],
    //     freshMonths: ['July', 'August', 'September'],
    //     location: 'New York',
    // },
    // {
    //     name: 'Herbs',
    //     type: 'VEGETABLE',
    //     storageMonths: [],
    //     freshMonths: ['July', 'August', 'September'],
    //     location: 'New York',
    // },
    {
      name: 'Kale',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [9, 10],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Lettuce',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [5, 6, 7, 8, 9, 10],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Leeks',
      type: 'VEGETABLE',
      storageMonths: [11, 12],
      freshMonths: [8, 9, 10],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Onions',
      type: 'VEGETABLE',
      storageMonths: [1, 2, 3, 4, 5, 6, 7, 11, 12],
      freshMonths: [8, 9, 10],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Parsnips',
      type: 'VEGETABLE',
      storageMonths: [1, 2, 3],
      freshMonths: [4, 5, 10, 11, 12],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Peas',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [6, 7, 9, 10],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Peppers',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [7, 8, 9, 10],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Potatoes',
      type: 'VEGETABLE',
      storageMonths: [1, 2, 3, 4, 5, 6, 11, 12],
      freshMonths: [7, 8, 9, 10],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Pumpkins',
      type: 'VEGETABLE',
      storageMonths: [11],
      freshMonths: [9, 10],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Radishes',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [5, 6, 7, 8, 9, 10],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Rhubarb',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [5, 6, 7],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Spinach',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [5, 6, 7, 8, 9, 10],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Squash, Summer',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [5, 6, 7, 8, 9, 10],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Squash, Winter',
      type: 'VEGETABLE',
      storageMonths: [1, 2, 11, 12],
      freshMonths: [8, 9, 10],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Swiss Chard',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [6, 7, 8, 9, 10],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Tomatoes',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [7, 8, 9, 10],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Turnips',
      type: 'VEGETABLE',
      storageMonths: [1, 2, 11, 12],
      freshMonths: [8, 9, 10],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Turnip Greens',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [5, 6, 7, 8],
      location: 'New York',
      generalInfo: '',
    },
  ];

  const fruits = [
    {
      name: 'Apples',
      type: 'FRUIT',
      storageMonths: [1, 2, 3, 4, 5, 6, 11, 12],
      freshMonths: [7, 8, 9, 10],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Blackberries',
      type: 'FRUIT',
      storageMonths: [],
      freshMonths: [8],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Blueberries',
      type: 'FRUIT',
      storageMonths: [],
      freshMonths: [7, 8, 9],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Cantaloupes',
      type: 'FRUIT',
      storageMonths: [],
      freshMonths: [8, 9],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Cherries',
      type: 'FRUIT',
      storageMonths: [],
      freshMonths: [7],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Currants',
      type: 'FRUIT',
      storageMonths: [],
      freshMonths: [8],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Grapes',
      type: 'FRUIT',
      storageMonths: [],
      freshMonths: [9, 10],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Peaches',
      type: 'FRUIT',
      storageMonths: [],
      freshMonths: [7, 8, 9],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Pears',
      type: 'FRUIT',
      storageMonths: [1, 2, 11, 12],
      freshMonths: [9, 10],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Plums',
      type: 'FRUIT',
      storageMonths: [],
      freshMonths: [7, 8, 9],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Prunes',
      type: 'FRUIT',
      storageMonths: [],
      freshMonths: [9, 10],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Strawberries',
      type: 'FRUIT',
      storageMonths: [],
      freshMonths: [6, 7],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Raspberries',
      type: 'FRUIT',
      storageMonths: [],
      freshMonths: [7, 9, 10],
      location: 'New York',
      generalInfo: '',
    },
    {
      name: 'Watermelon',
      type: 'FRUIT',
      storageMonths: [],
      freshMonths: [9, 10],
      location: 'New York',
      generalInfo: '',
    },
  ];

  vegetables.forEach(item => {
    const node = {
      name: item.name,
      type: item.type,
      storageMonths: item.storageMonths,
      freshMonths: item.freshMonths,
      location: item.location,
      generalInfo: item.generalInfo,
      nutritionInfo: item.nutritionInfo || '',
      id: createNodeId(`VEG-${item.name}`),
      internal: {
        type: item.type,
        contentDigest: createContentDigest(item),
      },
    };
    actions.createNode(node);
  });

  fruits.forEach(item => {
    const node = {
      name: item.name,
      type: item.type,
      storageMonths: item.storageMonths,
      freshMonths: item.freshMonths,
      location: item.location,
      generalInfo: item.generalInfo,
      nutritionInfo: item.nutritionInfo || '',
      id: createNodeId(`FRUIT-${item.name}`),
      internal: {
        type: item.type,
        contentDigest: createContentDigest(item),
      },
    };
    actions.createNode(node);
  });
};
