/**
 * General info: https://www.medicalnewstoday.com/articles/266765
 *
 * Nutrition Facts: https://fdc.nal.usda.gov/api-guide.html#bkmk-1
 *
 * https://www.gatsbyjs.org/docs/programmatically-create-pages-from-data/
 */

exports.sourceNodes = ({ actions, createNodeId, createContentDigest }) => {
  const vegetables = [
    {
      name: 'Asparagus',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [5, 6],
      location: 'New York',
      generalInfo:
        'Eat it raw or cooked, and in dishes such as soups, stews, salads, or on its own.',
      nutritionInfo:
        'Support heart and bone health, while the folate and iron that it contains may be especially beneficial during pregnancy.',
    },
    {
      name: 'Beans, String',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [7, 8, 9, 10],
      location: 'New York',
      generalInfo: '',
      nutritionInfo:
        'Rich source of vitamins A, C, and K, and of folic acid and fiber. They have similar nutritional benefits to snap peas and okra.',
    },
    {
      name: 'Beans, Shell',
      type: 'VEGETABLE',
      storageMonths: [1, 2, 3, 4, 5, 6, 7],
      freshMonths: [9, 10, 11, 12],
      location: 'New York',
      generalInfo: '',
      nutritionInfo:
        'Rich source of vitamins A, C, and K, and of folic acid and fiber. They have similar nutritional benefits to snap peas and okra.',
    },
    {
      name: 'Beets',
      type: 'VEGETABLE',
      storageMonths: [1, 2, 12],
      freshMonths: [6, 7, 8, 9, 10, 11],
      location: 'New York',
      generalInfo: '',
      nutritionInfo:
        'Reduce blood pressure, improve digestion, and lower the risk of diabetes.',
    },
    {
      name: 'Beet Greens',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [5, 6, 7, 8, 9],
      location: 'New York',
      generalInfo: '',
      nutritionInfo:
        'Reduce blood pressure, improve digestion, and lower the risk of diabetes.',
    },
    {
      name: 'Broccoli',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [6, 7, 8, 9, 10, 11],
      location: 'New York',
      generalInfo:
        'Broccoli has a reputation as a superfood. It is low in calories but contains a wealth of nutrients and antioxidants that support many aspects of human health.',
      nutritionInfo: '',
    },
    {
      name: 'Brussels Sprouts',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [9, 10, 11],
      location: 'New York',
      generalInfo:
        'Brussels sprouts are a staple of Christmas and Thanksgiving dinner. However, including more of these low calorie, nutritionally dense vegetables in the diet could provide significant health benefits.',
      nutritionInfo:
        'Brussels sprouts are an excellent source of protein, and just 88 grams (g), or 1 cup, of raw Brussels sprouts meets the National Institutes of Health’s (NIH) recommended daily requirements for vitamin C and vitamin K.',
    },
    {
      name: 'Cabbage',
      type: 'VEGETABLE',
      storageMonths: [1, 2, 3, 12],
      freshMonths: [5, 6, 7, 8, 9, 10, 11],
      location: 'New York',
      generalInfo:
        'Cruciferous vegetables like cabbage, kale, and broccoli are notorious for being chock-full of beneficial nutrients. If you are trying to improve your diet, cruciferous vegetables are a good place to start.',
      nutritionInfo:
        'Cabbage helps protect against radiation, prevent cancer, and reduce heart disease risk.',
    },
    {
      name: 'Carrots',
      type: 'VEGETABLE',
      storageMonths: [1, 2, 3, 12],
      freshMonths: [6, 7, 8, 9, 10, 11],
      location: 'New York',
      generalInfo: '',
      nutritionInfo:
        'Carrots are rich in vitamins, minerals, and fiber. They are also a good source of antioxidants.',
    },
    {
      name: 'Cauliflower',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [8, 9, 10, 11],
      location: 'New York',
      generalInfo: '',
      nutritionInfo:
        'Cauliflower is a cruciferous vegetable that is naturally high in fiber, B-vitamins, antioxidants, and phytonutrients that protect against cancer.',
    },
    {
      name: 'Celery',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [8, 9, 10],
      location: 'New York',
      generalInfo:
        'Celery is part of the Apiaceae family, which includes carrots, parsnips, parsley, and celeriac. Its crunchy stalks make the vegetable a popular low-calorie snack, and it may provide a range of health benefits.',
      nutritionInfo:
        'The fiber in celery can benefit the digestive and cardiovascular systems. Celery also contains antioxidants that may play a role in preventing disease.',
    },
    {
      name: 'Collard Greens',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [7, 8, 9, 10, 11, 12],
      location: 'New York',
      generalInfo:
        'Collard greens are part of the cruciferous vegetable family. They contain nutrients that can play an important role in a healthful diet.',
      nutritionInfo: '',
    },
    {
      name: 'Corn',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [7, 8, 9, 10],
      location: 'New York',
      generalInfo:
        'Corn is in everything from soda to cereal. However, corn has nutritional benefits, and there is no evidence that it is harmful to health.',
      nutritionInfo: '',
    },
    {
      name: 'Cucumbers',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [7, 8, 9],
      location: 'New York',
      generalInfo:
        'Cucumbers have a mild, refreshing taste and a high water content. They can help relieve dehydration and are pleasant to eat in hot weather. People eat cucumber as a savory food, but it is a fruit. It also features in some beauty products.',
      nutritionInfo: 'GOod for hydration, bone health, cardiovascular health',
    },
    {
      name: 'Eggplant',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [8, 9, 10],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    // {
    //     name: 'Fennel',
    //     type: 'VEGETABLE',
    //     storageMonths: [],
    //     freshMonths: ['July', 'August', 'September'],
    //     location: 'New York',
    // },
    // {
    //     name: 'Herbs',
    //     type: 'VEGETABLE',
    //     storageMonths: [],
    //     freshMonths: ['July', 'August', 'September'],
    //     location: 'New York',
    // },
    {
      name: 'Kale',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [9, 10],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Lettuce',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [5, 6, 7, 8, 9, 10],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Leeks',
      type: 'VEGETABLE',
      storageMonths: [11, 12],
      freshMonths: [8, 9, 10],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Onions',
      type: 'VEGETABLE',
      storageMonths: [1, 2, 3, 4, 5, 6, 7, 11, 12],
      freshMonths: [8, 9, 10],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Parsnips',
      type: 'VEGETABLE',
      storageMonths: [1, 2, 3],
      freshMonths: [4, 5, 10, 11, 12],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Peas',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [6, 7, 9, 10],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Peppers',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [7, 8, 9, 10],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Potatoes',
      type: 'VEGETABLE',
      storageMonths: [1, 2, 3, 4, 5, 6, 11, 12],
      freshMonths: [7, 8, 9, 10],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Pumpkins',
      type: 'VEGETABLE',
      storageMonths: [11],
      freshMonths: [9, 10],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Radishes',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [5, 6, 7, 8, 9, 10],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Rhubarb',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [5, 6, 7],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Spinach',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [5, 6, 7, 8, 9, 10],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Squash, Summer',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [5, 6, 7, 8, 9, 10],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Squash, Winter',
      type: 'VEGETABLE',
      storageMonths: [1, 2, 11, 12],
      freshMonths: [8, 9, 10],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Swiss Chard',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [6, 7, 8, 9, 10],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Tomatoes',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [7, 8, 9, 10],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Turnips',
      type: 'VEGETABLE',
      storageMonths: [1, 2, 11, 12],
      freshMonths: [8, 9, 10],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Turnip Greens',
      type: 'VEGETABLE',
      storageMonths: [],
      freshMonths: [5, 6, 7, 8],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
  ];

  const fruits = [
    {
      name: 'Apples',
      type: 'FRUIT',
      storageMonths: [1, 2, 3, 4, 5, 6, 11, 12],
      freshMonths: [7, 8, 9, 10],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Blackberries',
      type: 'FRUIT',
      storageMonths: [],
      freshMonths: [8],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Blueberries',
      type: 'FRUIT',
      storageMonths: [],
      freshMonths: [7, 8, 9],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Cantaloupes',
      type: 'FRUIT',
      storageMonths: [],
      freshMonths: [8, 9],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Cherries',
      type: 'FRUIT',
      storageMonths: [],
      freshMonths: [7],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Currants',
      type: 'FRUIT',
      storageMonths: [],
      freshMonths: [8],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Grapes',
      type: 'FRUIT',
      storageMonths: [],
      freshMonths: [9, 10],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Peaches',
      type: 'FRUIT',
      storageMonths: [],
      freshMonths: [7, 8, 9],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Pears',
      type: 'FRUIT',
      storageMonths: [1, 2, 11, 12],
      freshMonths: [9, 10],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Plums',
      type: 'FRUIT',
      storageMonths: [],
      freshMonths: [7, 8, 9],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Prunes',
      type: 'FRUIT',
      storageMonths: [],
      freshMonths: [9, 10],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Strawberries',
      type: 'FRUIT',
      storageMonths: [],
      freshMonths: [6, 7],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Raspberries',
      type: 'FRUIT',
      storageMonths: [],
      freshMonths: [7, 9, 10],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
    {
      name: 'Watermelon',
      type: 'FRUIT',
      storageMonths: [],
      freshMonths: [9, 10],
      location: 'New York',
      generalInfo: '',
      nutritionInfo: '',
    },
  ];

  vegetables.forEach(item => {
    const node = {
      name: item.name,
      type: item.type,
      storageMonths: item.storageMonths,
      freshMonths: item.freshMonths,
      location: item.location,
      generalInfo: item.generalInfo,
      nutritionInfo: item.nutritionInfo || '',
      id: createNodeId(`VEG-${item.name}`),
      internal: {
        type: item.type,
        contentDigest: createContentDigest(item),
      },
    };
    actions.createNode(node);
  });

  fruits.forEach(item => {
    const node = {
      name: item.name,
      type: item.type,
      storageMonths: item.storageMonths,
      freshMonths: item.freshMonths,
      location: item.location,
      generalInfo: item.generalInfo,
      nutritionInfo: item.nutritionInfo || '',
      id: createNodeId(`FRUIT-${item.name}`),
      internal: {
        type: item.type,
        contentDigest: createContentDigest(item),
      },
    };
    actions.createNode(node);
  });
};
